### ISSUE TITLE
Error: Wrong version of Terraform is installed. NPK requires Terraform v0.11.

### ISSUE THREAD

**Issue by robellegate** [Coalfire-Research/npk#146]
Hello, I have Terraform v0.11.14 installed via Homebrew on my Mac, yet when I try to run `./deploy.sh` or `deploy-selfhost.sh`, I get the above error message. I have tried using the non-default binary positional parameter, but that doesn't seem to work.

Here's some info from my system:

```bash
$ git remote -v
origin  https://github.com/Coalfire-Research/npk (fetch)
origin  https://github.com/Coalfire-Research/npk (push)

$ git fetch; git pull; git status
Current branch master is up to date.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]%Creset" --decorate | head -5
f74c343 (HEAD -> master, origin/master, origin/dev, origin/HEAD)\ Merge remote-tracking branch 'origin/dependabot/npm_and_yarn/terraform-selfhost/compute-node/axios-0.21.1' into dev\ [Brad Woodward]
d81b9ac\ Move keyspace to wrapper, change unzip to 7z\ [Brad Woodward]
a67d089 (origin/dependabot/npm_and_yarn/terraform-selfhost/compute-node/axios-0.21.1)\ Bump axios from 0.18.1 to 0.21.1 in /terraform-selfhost/compute-node\ [GitHub]
23b906d\ Updated Axios\ [GitHub]
80e1a6e\ Add hashType to keyspace args\ [Brad Woodward]

$ brew shellenv                          
export HOMEBREW_PREFIX="/usr/local";
export HOMEBREW_CELLAR="/usr/local/Cellar";
export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/usr/local/share/info:${INFOPATH:-}";

$ brew info terraform@0.11         
terraform@0.11: stable 0.11.14 (bottled) [keg-only]
Tool to build, change, and version infrastructure
https://www.terraform.io/
/usr/local/Cellar/terraform@0.11/0.11.14 (6 files, 42.5MB) *
  Poured from bottle on 2021-03-22 at 14:03:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/terraform@0.11.rb
License: MPL-2.0
==> Dependencies
Build: go ✔, gox ✘
==> Caveats
terraform@0.11 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have terraform@0.11 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/terraform@0.11/bin:$PATH"' >> ~/.zshrc

==> Analytics
install: 347 (30 days), 1,117 (90 days), 6,668 (365 days)
install-on-request: 348 (30 days), 1,117 (90 days), 6,661 (365 days)
build-error: 0 (30 days)

$ brew link --overwrite terraform@0.11                 
Warning: Already linked: /usr/local/Cellar/terraform@0.11/0.11.14
To relink:
  brew unlink terraform@0.11 && brew link --force terraform@0.11

$ which terraform; terraform -v            
/usr/local/bin/terraform
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.14.8. You can update by downloading from www.terraform.io/downloads.html

$ ./deploy-selfhost.sh                                            
Error: Wrong version of Terraform is installed. NPK requires Terraform v0.11.
-> Note: A non-default binary can be specified as a positional script parameter:
-> e.g: ./deploy-selfhost.sh <terraform-v0.11-path>


Install missing components, then try again.


$ ./deploy-selfhost.sh $(which terraform)
Error: Wrong version of Terraform is installed. NPK requires Terraform v0.11.
-> Note: A non-default binary can be specified as a positional script parameter:
-> e.g: ./deploy-selfhost.sh <terraform-v0.11-path>


Install missing components, then try again.


$ ./deploy-selfhost.sh /usr/local/opt/terraform@0.11/bin/terraform 
Error: Wrong version of Terraform is installed. NPK requires Terraform v0.11.
-> Note: A non-default binary can be specified as a positional script parameter:
-> e.g: ./deploy-selfhost.sh <terraform-v0.11-path>


Install missing components, then try again.


$ date -u
Mon Mar 22 18:17:20 UTC 2021
```

If there's any additional information I can provide, please let me know. I'm excited to try using this project!

**Comment by c6fc** [comment]
Ahh, there's a bug on line 35 of deploy.sh where `terraform` is used instead of `$TERBIN`. I'll get it fixed.

**Comment by c6fc** [comment]
@robellegate I've added a fix to the dev branch. Try checking out that branch and deploying. If that fixes it, I'll push it to Master.

**Comment by c6fc** [comment]
I've pushed this to master.

**Comment by robellegate** [comment]
Hi @c6fc, I'm sorry I haven't gotten back to you sooner. I just tested out your change, and unfortunately, it seems that I still get the Terraform version error. At least on my version of macOS, I believe the issue is that the output of `wc -l` adds extra padding that makes it not equal to 1.

```bash
bash-3.2$ /usr/local/bin/terraform -v | grep v0.11 | wc -l | hexdump 
0000000 20 20 20 20 20 20 20 31 0a                     
0000009
bash-3.2$ echo 1 | hexdump
0000000 31 0a                                          
0000002
```

Another possible way of fixing it would be to skip using the `wc` command and instead use `grep -c`.

```bash
bash-3.2$ terraform -v | grep -c v0.11 | hexdump
0000000 31 0a                                          
0000002
```

Please let me know what you think.
